### ISSUE TITLE
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.date'

### ISSUE THREAD

**Issue by zhiwenyou103** [arianpasquali/tilse#1]
Hello! I read this repo and try to reproduce the results. However, I encountered an error when I run `predict-timelines` command. It shows:

Traceback (most recent call last):
  File "./bin/predict-timelines", line 89, in <module>
    returned_timelines, scores = algorithm.run(news_corpora, reference_timelines)
  File "/Users/Uzw/tilse/bin/../tilse/models/models.py", line 74, in run
    new_results_rouge, new_results_date, new_returned_timelines = self._run_for_one(t, corpora,
  File "/Users/Uzw/tilse/bin/../tilse/models/models.py", line 96, in _run_for_one
    timeline_properties = self.get_timeline_properties(timeline)
  File "/Users/Uzw/tilse/bin/../tilse/models/models.py", line 125, in get_timeline_properties
    groundtruth_dates = sorted(list(timeline.get_dates()))
TypeError: '<' not supported between instances of 'NoneType' and 'datetime.date'

I already changed the corpus path in each config file. My running command is `./bin/predict-timelines /Users/Uzw/tilse/configs/timeline17/chieu_timeline17.json`. 
I assume it looks fine. I really don't know which part is missing. My python version is 3.7.3. spacy==2.0.12. en-core-web-sm==2.0.0. 
I hope you could give me some instructions about running process. That would be really helpful!!! 
Thank you in advance!

**Comment by zhiwenyou103** [comment]
I solved this issue. Thanks!
